IF
  Global("CDItems","ar0334",1)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("quiver04",Player1,0,0,0) // Case of Plenty +2
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",2)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("helm30",Player1,3,0,0) // Thieves' Hood
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",3)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("helm32",Player1,3,0,0) // Helm of the Rock
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",4)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("brac25",Player1,0,0,0) // Wondrous Gloves
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",5)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("brac23",Player1,1,1,0) // Blessed Bracers
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",6)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("tome02",Player1,1,0,0) // Clay Golem Manual
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",7)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("clck31",Player1,0,0,0) // Improved Cloak of Protection +2
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",8)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("chan20",Player1,3,0,0) // White Dragon Scale
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",9)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("chan19",Player1,0,0,0) // Aslyferund Elven Chain +5
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",10)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("slng09",Player1,0,1,0) // Erinne Sling +5
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",11)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("quiver03",Player1,0,0,0) // Quiver of Plenty +2
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",12)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("blun30c",Player1,0,0,0) // Flail of Ages +4
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",13)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("blun27",Player1,0,0,0) // Club of Detonation +5
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",14)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("sper12",Player1,0,0,0) // Ixil's Spike +6
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END

IF
  Global("CDItems","ar0334",15)
  Global("ForgeStuff","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("CDItems","ar0334",0)
    GiveItemCreate("dagg22",Player1,0,0,0) // Dagger of the Star +5
    ActionOverride("wsmith01",StartDialogueNoSet([PC]))
END